//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Activity
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [DataType(DataType.Time)]
        public string Time { get; set; }

        public int ActivityTypeID { get; set; }
        public virtual ActivityType ActivityType { get; set; }

        public int ActivityStatusID { get; set; }
        public virtual ActivityStatus ActivityStatus { get; set; }

        public int PersonID { get; set; }
        public string PersonName { get; set; }

    }
}
