//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public int ID { get; set; }
        public string GuestName { get; set; }
        public string Quantity { get; set; }
        public int EventId { get; set; }
        public int ContributionTypeID { get; set; }
    
        public virtual ContributionType ContributionType { get; set; }
    }
}
