//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesEntities : DbContext
    {
        public MoviesEntities()
            : base("name=MoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activity { get; set; }
        public DbSet<ActivityStatus> ActivityStatus { get; set; }
        public DbSet<ActivityType> ActivityType { get; set; }
        public DbSet<Contribution> Contribution { get; set; }
        public DbSet<ContributionType> ContributionType { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<PersonRole> PersonRole { get; set; }
    }
}
